Repository y10b/6-Photo-2-BE, pull requests merged in 2025-05, with the labels that each got.

#21 [기능] 회원가입/로그인, 포인트 연동, 시딩 & 에러핸들러 개선
  .http/auth.http
  src/app.js
  src/middlewares/error.middleware.js
  src/prisma/schema.prisma
  src/services/authService.js
  src/utils/memo
Labels: ⭐Feat

#23 feat: 카드 조회 API 수정 및 생성 API 구현
  src/repositories/photoRepository.js
Labels: ⭐Feat

#29 [기능] 사용자 인증 및 정보 관리 API 구현
  .http/auth.http
  .http/user.http
  .prettierrc
  src/app.js
  src/controllers/authController.js
  src/controllers/userController.js
  src/repositories/userRepository.js
  src/routes/authRoutes.js
  src/routes/userRoutes.js
  src/services/authService.js
  src/services/userService.js
Labels: ⭐Feat

#30 [수정] 사용자 정보 응답에서 포인트 중복 제거
  .http/user.http
  src/services/authService.js
Labels: 🩹Fix

#31 refactor: 카드 조회 중 getMyCards와 getMyIDLECards를 하나의 기능으로 통합
  src/controllers/photoController.js
  src/repositories/photoRepository.js
  src/routes/photoRoutes.js
  src/services/photoService.js
Labels: 🛠️Refactor

#41 fix: 에러 코드 타입 검사
  src/middlewares/error.middleware.js
Labels: 🩹Fix

#47 fix: 포토카드 조회 필터링 로직 및 업로드 파일 생성 오류 수정
  src/middlewares/upload.middleware.js
  src/repositories/photoRepository.js
Labels: 🩹Fix

#52 feat: PhotoCard 모델에 creatorId 필드 추가 및 생성 제한 로직 수정
  src/prisma/migrations/20250530052646_add_creator_id_to_photo_card/migration.sql
  src/prisma/schema.prisma
  src/prisma/seed.js
  src/repositories/photoRepository.js
Labels: ⭐Feat
