Repository y10b/6-Photo-2-BE, pull requests merged in 2025-06, with the labels that each got.

#58 refactor: 포토카드 타입/상태명 수정
  src/repositories/photoRepository.js
Labels: 🛠️Refactor

#59 feat: 알림 교환 구현
  .http/exchange.http
  .http/notification.http
  .http/purchase.http
  src/repositories/exchangeRepository.js
  src/services/exchangeService.js
Labels: ⭐Feat

#68 [Refactor] 에러 메시지 통일 및 구조 리팩토링
  .DS_Store
  src/.DS_Store
  src/controllers/authController.js
  src/controllers/pointController.js
  src/controllers/userController.js
  src/middlewares/.DS_Store
  src/middlewares/passport/localStrategy.js
  src/repositories/userRepository.js
  src/routes/authRoutes.js
  src/routes/userRoutes.js
  src/services/authService.js
  src/services/userService.js
Labels: 🛠️Refactor

#69 chore: uuid 패키지 설치 및 업로드 미들웨어 수정
  package-lock.json
  package.json
  src/middlewares/upload.middleware.js
  src/repositories/photoRepository.js
Labels: ⚙️Chore

#72 feat: 판매 페이지에서 솔드아웃 타입 넘겨주도록 수정
  src/repositories/photoRepository.js
Labels: ⭐Feat

#78 refactor: 중복 함수 제거 및 README.md 작성
  README.md
  src/controllers/photoController.js
  src/repositories/photoRepository.js
  src/routes/photoRoutes.js
  src/services/photoService.js
Labels: 📜Docs, 🛠️Refactor

#79 fix: README 작업물 이미지 추가
  README.md
  uploads/474b5853-eb7d-46ad-a71f-35514759f5d3-1748909548817.jpeg
  uploads/_ (1)-1748850025812.jpeg
Labels: 🩹Fix

#85 fix: README 이미지 폴더 추가
  public/dev/sale-detail.png
  public/dev/sale-list.png
  public/dev/sale-registeration.png
Labels: 🩹Fix

#98 fix: 판매 포토카드 전체 정렬로 로직 수정
  src/repositories/photoRepository.js
Labels: 🩹Fix
